---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
generator:
  name: "NewScalaProject"
  group: "atomist-rugs"
  artifact: "scala-project"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist-rugs/scala-project.git"
    branch: "master"
    sha: "ecce4eb"
  parameters:
    - "group_id": "jessitron"
    - "package": "com.jessitron.kats"
    - "project_name": "kats-parser"

---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
editor:
  name: "jessitron.microlib-TreeNodePrinter.BringIn"
  group: "jessitron"
  artifact: "microlib-TreeNodePrinter"
  version: "0.1.0"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"
  parameters:
    - "package": "com.jessitron.kats"

---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
editor:
  name: "WrapFunctionBody"
  group: "jessitron"
  artifact: "kats-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:jessitron/kats-rugs.git"
    branch: "master"
    sha: "26ac88b*"

---
kind: "operation"
client: "rug-cli 0.23.1-SNAPSHOT"
editor:
  name: "atomist-rugs.scala-editors.MakeRugLanguageExtension"
  group: "atomist-rugs"
  artifact: "scala-editors"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist-rugs/scala-editors"
    branch: "master"
    sha: "e5b63eb*"
  parameters:
    - "package": "com.jessitron.kats"
    - "type_name": "Elm"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.1-JESS"
editor:
  name: "ConvertExistingProjectToRugArchive"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.0-20170606145959"
  origin:
    repo: "git@github.com:jessitron/kats-parser.git"
    branch: "master"
    sha: "5bafe4a"
  parameters:
    - "archiveName": "parser"
    - "groupId": "jessitron"
    - "version": "0.1.0"

